services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: jwt-backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - jwt-net

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: jwt-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - jwt-net

networks:
  jwt-net:
    driver: bridge 